### ISSUE TITLE
Add currency tracking to inventory

### ISSUE THREAD

**Issue by arbron** [koboldpress/black-flag#290]
- [x] Add currency to inventory lists
- [ ] ~~Automatically create base currencies when actor is created~~
- [x] Enable add button to introduce new currencies
   - [x] Display list of currencies with input box, will add whatever you select to currency count
   - [x] If currency type currently exists, it will just add to it
- [x] Merge like-currencies when dropped onto sheet
- [x] Automatically sort currencies by value
